### ISSUE TITLE
Fix Interactable scheme

### ISSUE THREAD

**Issue by 60and80** [dubpirate/BigBrainBots#27]
Current scheme is a bit janky, should ideally be able to handle:
- [x] Each interactable being linked to multiple triggerables
- [ ] Each triggerable accepting more complex logic than && (may or may not be necessary)

**Comment by dubpirate** [comment]
@60and80 I think you should make adding the 'More Complex Logic' to it's own issue and calling this one done. It has been a considerable amount of work put in already.
