### ISSUE TITLE
Add Level Models (Tutorial, Zeuthian lvl 1 & 2)

### ISSUE THREAD

**Issue by dubpirate** [dubpirate/BigBrainBots#44]
Convert the current gray boxed levels into the designers more finished ones.

 - [x] Tutorial Level
 - [x] Zeuthian Station Level 1
 - [x] Zeuthian Station Level 2

**Comment by YargleSnarf** [comment]
The new maps can be found in the geometry folder. Each level will have its own folder with the map and an assets folder.
These can be moved anytime, just wanted to keep the old maps as reference for where things should go
