### ISSUE TITLE
Adding Interactable Models

### ISSUE THREAD

**Issue by dubpirate** [dubpirate/BigBrainBots#47]
- [x] Lever
- [x] Button
- [x] Pressure Plate
- [x] Battery Bot Items

Someone added the Button Mesh without tagging this issue.

**Comment by dubpirate** [comment]
Need to update with Hold-Lock pads. No meshes for buttons. Going to early merge just to have what progress we've already got.

**Comment by YargleSnarf** [comment]
Button meshes are in
